### ISSUE TITLE
Oncor is incorrectly identified as agent of open incentive

### ISSUE THREAD

**Issue by RMBoys** [NREL/developer.nrel.gov#100]
Nissan, not Oncor, is the agent for a listing recently added to the Laws and Incentives - TX database.
[DOE EE citation error.docx](https://github.com/NREL/developer.nrel.gov/files/2784305/DOE.EE.citation.error.docx)

**Comment by mrahill** [comment]
@RMBoys – Thank you for bringing this to our attention. This issue was resolved, and that incentive no longer exists on the Texas page at https://afdc.energy.gov/laws/state_summary?state=TX.
