### ISSUE TITLE
PvWatts Address format 

### ISSUE THREAD

**Issue by mailbox01** [NREL/developer.nrel.gov#111]
what is appropriate address format for PvWatts API call. 

Since i am calling the API for Perth , WA , but it seems API not resolving the input address e.g. "6 Michael Cres,  Boya,WA,6056" , in this case API is returning the data of  station "Nantes/FRA" rather than WA station. I am using the dataset="intl"

what is wrong in the input / or suggest the proper input format to get the correct data output

Thanks

**Comment by reger** [comment]
@mailbox01 apologies for this **really** falling through the cracks. The only explanation I have is that pvwatts is geocoding your address string incorrectly. I was able to get it to use the Swanbourne, WA station if I sent in `6 Michael Cres, Boya,Western Australia,6056` as the `address`. Not that it helps you now. Again, apologies.
