### ISSUE TITLE
Solar Resource data for Pune, India

### ISSUE THREAD

**Issue by plunavat** [NREL/developer.nrel.gov#112]
Hello,

I am not getting solar resource data for following lat and lon

[https://developer.nrel.gov/api/solar/solar_resource/v1.json?api_key=DEMO_KEY&lat=18.52&lon=73.79](url)
could you please help

Regards,
Pranav

**Comment by reger** [comment]
@plunavat that API only has data for the US. You might take a look at the [NSRDB APIs](https://developer.nrel.gov/docs/solar/nsrdb/) to see if they have the data you are looking for.
