### ISSUE TITLE
Wind Toolkit Data API Returning Unspecified Error

### ISSUE THREAD

**Issue by bmosov01** [NREL/developer.nrel.gov#122]
I have been periodically extracting data for resource assessment analysis for over a year, but in the last week my API calls started returning the following message:

An error has occurred. Please consult with your administrator.
Your support ID is: 15679877088887868874
[Go Back]

My API call that returned the above message was:
https://developer.nrel.gov/api/wind-toolkit/wind/wtk_download.csv?api_key=MY_KEY&wkt=POINT(-100.24%2030.728)&attributes=wind_speed,wind_direction,temperature,pressure&names=2010&leap_day=false&email=MY_EMAIL&utc=true
(of course, MY_KEY and MY_EMAIL contained the appropriate values)

Have there been any recent changes to the API interface or is there a known service interruption? Are others able to generate successful API calls? If so, could you please provide an example? I also tried the call in the example on the documentation page (https://developer.nrel.gov/docs/wind/wind-toolkit/wind-toolkit-extract/) and got the same error.

Thanks for any help you can provide.

**Comment by PjEdwards** [comment]
Hi Brock, Yes, we had a service outage for the past few days, and I was out of town and unable to resolve it until today. Should be operational now. If you have further issues let me know!
Paul
