### ISSUE TITLE
Physical Model 3 pressure units

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#137]
I am using the physical model 3 API to get typical weather data for various locations, specifically: 

https://developer.nrel.gov.api/solar/nsrdb_psm3_download.csv

I have noticed an issue with the surface_pressure datatype, which is that the values provided do not appear to be consistent with the units of measure. The response indicates that the units of measure are mbar (this is also what has historically been used in TMY data sets), but the values are...100s of millibars, I think? They are values around 10 (10.1, 10.2, etc). 

Can someone confirm if these units are correct, if a change has been made recently, or if something else is going on? I want to make sure this is going to be a consistent, persistent change before I edit my code. Thank you!

**Comment by PjEdwards** [comment]
Yeah, that does look wrong. Let me figure out what's going on and get back to you.

**Comment by PjEdwards** [comment]
Fix has been deployed. We had some internal disconnects on what units were in there, and hence they were being erroneously scaled. Thanks for the heads up!

**Comment by PjEdwards** [comment]
@reger can close at will
