### ISSUE TITLE
Issue with air temperature data for Oakland Metropolitan Airport

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#139]
The specific API call I am using is:

https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?api_key=[api_key]&attributes=air_temperature,surface_pressure,dew_point&email=[email]&wkt=POINT(-122.2642+37.7983)&names=tmy&utc=false&interval=60

Starting on November 30 16:00, the data returned for this call appears to switch from degC to degC x10; the hourly readings for November 30th are as follows:

7, 6, 5, 5, 4, 4, 4, 4, 6, 8, 10, 11, 12, 12, 12, 11, **126, 114, 110, 104, 98, 95, 95, 95**

This issue appears to persist until 12/31 15:00, at which point it switches back to simply degC. There appears to be a related issue with dewpoint, but it doesn't appear to be a change in units; rather, it appears to be an issue related to the calculation of dew point. The hourly readings for November 30th are:

-5,-4,-4,-3,-3,-3,-3,-4,-3,-4,-4,-4,-4,-3,-3,-2,**83,84,89,92,93,93,92,92**

Please let me know if you need any additional clarifications on the issue. Thank you!

**Comment by PjEdwards** [comment]
Let me raise this with the modeling team and see if they can help isolate the issue. Thanks!

**Comment by craftj2** [comment]
I have now also found this problem on TMY for Portland-Hillsboro Airport. I have observed now in both cases the issue exists where the source year is 2018. Hopefully that should help the modeling team isolate the issue!

**Comment by PjEdwards** [comment]
Thanks again for identifying and sharing the issue. It's on the issue list, but not likely to get fixed in the short term due to the work and time involved in re-running.

**Comment by reger** [comment]
@PjEdwards @craftj2 okay to close this now?

**Comment by craftj2** [comment]
Yes this has been resolved, thank you!
