### ISSUE TITLE
CORS error on performing XMLHTTP GET request to PVWatts v6 api

### ISSUE THREAD

**Issue by Dhawaldeep** [NREL/developer.nrel.gov#141]
When the application with origin 'https://heliware.co.in' tries to access using XMLHttprequest to https://developer.nrel.gov/api/pvwatts/v6.json?params it gets blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

The application has a SSL certificate even then it throws a CORS error.

**Comment by reger** [comment]
@GUI can you take a look at this?

**Comment by Dhawaldeep** [comment]
@reger Can you please tell me the repository which I have to use?

**Comment by reger** [comment]
@Dhawaldeep not sure what you are asking

**Comment by Dhawaldeep** [comment]
Oh sorry I thought you were asking me to see repositoried pinned in @GUI account but instead you were calling @GUI

**Comment by reger** [comment]
yeah :) he's on my team here, I was asking him to look into it

**Comment by GUI** [comment]
@Dhawaldeep: Are you passing any HTTP headers into the request? That might explain why you're getting an error on the CORS pre-flight request. If you can avoid passing HTTP headers in, then that should avoid the need for the pre-flight request on GET requests. If you're passing the API key in via the HTTP header, try passing the API key via the [GET query parameter](https://developer.nrel.gov/docs/api-key/) instead. If that doesn't do the trick, let us know.

**Comment by Dhawaldeep** [comment]
Yes I checked, the angular http interceptor was sending one unwanted authorization header. Thanks a lot.
