### ISSUE TITLE
How to set-up data rate for the WindToolKit?

### ISSUE THREAD

**Issue by TimurDela** [NREL/developer.nrel.gov#145]
The map Query tool allows to request data binned per hour or by 5 minutes intervals but the API reference does not explain how to set the data interval and sends 5' bins per default.

I know I can aggregate 5' data to get hourly data but that doesn't seem to be an optimal use of bandwidth.

Is there a request parameter that would allow downloading hourly data?
https://developer.nrel.gov/docs/wind/wind-toolkit/wind-toolkit-extract/

Thank you

**Comment by PjEdwards** [comment]
Yeah, you're right. THe documentation is missing some detail there. I'll have to rectify that! In the meantime, you can use the `interval=5` or `interval=60` parameter to accomplish it. Just copying the example from the docs and adding this looks like:

```
/api/wind-toolkit/wind/wtk_download.csv?api_key=DEMO_KEY&wkt=POINT(-104.23828125%2039.90973623453719)&attributes=wind_speed,wind_direction,power,temperature,pressure&names=2009&full_name=Sample User&email=sample@email.com&affiliation=Test Organization&reason=Example&interval=60
```

**Comment by TimurDela** [comment]
Thank you very much!
