### ISSUE TITLE
psm3_tmy_data - Does this format work?

### ISSUE THREAD

**Issue by cbest1990** [NREL/developer.nrel.gov#149]
Hello, I am able to get other api request to run, but can not get any API request for PSM TMY data following the example online:

GIVEN ONLINE: (/api/nsrdb_api/solar/nsrdb_psm3_tmy_download)

MY REQUEST:
URL <- "http://developer.nrel.gov/api/solar/nsrdb_psm3_tmy_download.csv?wkt=POINT(-97.1292+33.2164&attributes=dhi)&names=tmy-2018&full_name=CJBest&email=charles.best@uga.edu&affiliation=UGA&mailing_list=false&reason=research&utc=false&api_key= keyinfo"

req <- GET(url = URL)
stop_for_status(req)
test <- content(req)
test

I get back :  Error: Not Found (HTTP 404)

I am held up on building an app until I can move forward any feedback would be greatly appreciated.

Thank  you,
Charles Best

**Comment by kanderso-nrel** [comment]
Hi @cbest1990, I think you have two errors in your URL.  I believe the correct endpoint is `http://developer.nrel.gov/api/nsrdb_api/solar/nsrdb_psm3_tmy_download.csv` and you are missing the `nsrdb_api` part.  Also, you have the `attributes` info inside the `wkt` spec.  FYI the pvlib python package has [a function](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.iotools.get_psm3.html) to pull data from this api;  if you're a python user, it might be more convenient than building the URL manually.

**Comment by cbest1990** [comment]
Thank you for the response!
This is part of a project for an application I am building to be deployed on shiny.io so it has to be R.  

I discovered what the error was and was able to build the API. 

Thank you,
Charles Best
