### ISSUE TITLE
HSDS API URL Isssues?

### ISSUE THREAD

**Issue by ruikaitang** [NREL/developer.nrel.gov#151]
Hi, I'm just trying to work through the jupyter notebook hsds examples from (https://github.com/NREL/hsds-examples). However, it looks like I'm stuck on the literal first step, as I can't appear to access the API at all.

`import h5pyd`
`f = h5pyd.File(".hscfg", 'r')`
`print(list(f))`

The .hscfg file contains the following lines:

`hs_endpoint = https://developer.nrel.gov/api/hsds`
`hs_username = r************k@canada.ca`
`hs_password = *************************`
`hs_api_key = *************************`

where hs_password is the same as hs_api_key.

Attempting to run the code gives me a 400 error: OSError: [Errno 400] Invalid domain name. 

I'm not 100% sure the API key is valid, as it is quite old, so that might be the problem. However, Since I'm getting a domain error, it seems to me that the hs_endpoint url is wrong in some way, but I haven't been able to find any resources to specify the correct url, as the one I'm using the the one listed in the examples.

**Comment by MRossol** [comment]
@ruikaitang

Your .hsconfig file should look like this:
hs_endpoint = https://developer.nrel.gov/api/hsds
hs_username = 
hs_password = 
hs_api_key = *************************

You do not have a username or password.

The hs_api_key should be the api key from developer.nrel.gov

**Comment by ruikaitang** [comment]
Oh, I was provided with a username and password so I thought I needed to use them. Since those fields are left blank, are they necessary at all or can they be omitted in the .hsconfig file?

**Comment by MRossol** [comment]
@ruikaitang

They SHOULD be left blank. You should only provide the hs_endpoint and hs_api_key
