### ISSUE TITLE
"Request Too Large"

### ISSUE THREAD

**Issue by Sophieleamon** [NREL/developer.nrel.gov#154]
Hi all,

I'm hoping to streamline using the NREL API to download wind and solar profiles by state. I used the NREL Windtool kit to map out the polygon geometry for Ohio (for example) and then used that polygon for an API request.

I've gotten the error ""Request too large." Note that I am pulling a single year of data and only the power attribute. 

Is this error caused because there are more than 1000 points in the Ohio polygon and therefore with only a single state I am pulling too many points and exceeding my data limit? Is there a way around this?

Thanks all,
Sophie

**Comment by PjEdwards** [comment]
Hi Sophie, 
Yep, it's a simple matter of our available hardware limiting the total throughput we can manage. There is a guide that details the method applied and offers guidance for maximizing each request at https://developer.nrel.gov/docs/wind/wind-toolkit/guide/. Also we are currently working on a fully backwards compatible v2 version of this that will allow us to increase our rate limits. Look for that in mid June.

**Comment by Sophieleamon** [comment]
Thanks very much Paul for the quick response.

Is there a way of getting around this for a one-time pull, maybe planning a midnight request or setting a download timer? - We’re hoping to do a large modeling update and are trying to avoid a large number of manual small pulls.

Thanks for all your help on this. Stay safe,
Sophie

**Comment by PjEdwards** [comment]
The other option is to grab bulk raw data using HSDS... Check out https://github.com/NREL/hsds-examples.

Best,
Paul

**Comment by Sophieleamon** [comment]
Thank you, Paul.

Unfortunately, for this project, we’re only really able to use the converted shapes (MW) and it looks like HSDS only offers the raw weather data.

I have two remaining ideas for ways to bypass the data-limit - please let me know if either would be feasible:

1.       Is there documentation of the available API POINTs? If there was a list of API POINT coordinates, I could loop through a subset of that list of POINTS and not have to specify a POLYGON that exceeds the data limit.

a.       An example of what would be useful would be a list of API POINTs in a geographical region, ex. Ohio, or PG&E, or in any granular geographical grouping that we could clearly define.

2.       Barring this, is there someone at NREL who could make a larger query for us?

Thanks again for your help,
Sophie

**Comment by PjEdwards** [comment]
Yeah, [this file](https://data.nrel.gov/files/54/wtk_site_metadata.csv) lists both the coordinates and the state name (among other things) of each point. You can use this to generate a list of specific points to download and submit it in your request as a multi-point WKT. There is an example of the MULTIPOINT approach in [the NSRDB docs](https://developer.nrel.gov/docs/solar/nsrdb/guide/). That plus some math to determine the biggest request you can make as in the WIND toolkit guide previously linked should enable you to get what you're looking for in a small set of requests.

**Comment by Sophieleamon** [comment]
This is perfect. Thanks again.
Sophie

**Comment by PjEdwards** [comment]
No problem. Good luck!
