### ISSUE TITLE
PVWatts Tool for Historical Year

### ISSUE THREAD

**Issue by Sophieleamon** [NREL/developer.nrel.gov#155]
Hi, 

I'm hoping to use the PVWatts API to convert a irrandiance data from a specific year (2009). It looks like if you don't give it a file_id from a solar database query, that it will default to a TMY file.

I was looking to see if I could identify file_ids by year, but [this ](https://developer.nrel.gov/docs/solar/data-query-v1/) documentation appears not to differentiate by year. Is it possible to make this specification? Thanks, Sophie

**Comment by reger** [comment]
@Sophieleamon Apologies for the slow reply. The TMY files used by pvwatts are not yearly files, they are "typical meteorological years" meaning the values in them are averaged over a multiyear period. See https://nsrdb.nrel.gov/about/tmy for a full description.

I'm not as familiar with the NSRDB APIs, but they might have what you are looking for: https://developer.nrel.gov/docs/solar/nsrdb/
