### ISSUE TITLE
Request rejected

### ISSUE THREAD

**Issue by scottmn** [NREL/developer.nrel.gov#158]
Today I began experiencing an issue submitting a POST request to:

http://developer.nrel.gov/api/nsrdb_api/solar/nsrdb_psm3_tmy_download.csv

(using appropriate query string vals, email, api_key, etc.)

```
<html>

<head>
	<title>Request Rejected</title>
</head>

<body>An error has occurred. Please consult with your
	administrator.<br><br>Your support ID is: 5562235707991851251<br><br><a href='javascript:history.back();'>[Go
		Back]</a></body>

</html>
```

A GET request to the same URL works fine.  Is the POST no longer supported or is there an issue with the API at the moment?  Thanks!

**Comment by PjEdwards** [comment]
@scottmn Thanks for the heads up. I restored access to the POST and OPTIONS verbs just now. Let me know if you have any further trouble.
