### ISSUE TITLE
Dependabot Commit breaking circleci

### ISSUE THREAD

**Issue by PjEdwards** [NREL/developer.nrel.gov#161]
Doesn't like Rack update? Seems to be preventing deployment of latest documentation

**Comment by PjEdwards** [comment]
https://github.com/NREL/developer.nrel.gov/commit/4e538e30f65fbcbbfd68726f5917de7cc85599af

**Comment by PjEdwards** [comment]
@GUI @reger I believe this is the reason updates to docs aren't getting deployed? It would be really great if we could do whatever is needed to get these deployed. Let me know if I can help with anything?

**Comment by GUI** [comment]
@PjEdwards: Sorry about this! The CI setup on this project has gotten to be a bit of a mess between our internal Jenkins and left over CircleCI vestiges. Apologies this is blocking deploys, I'm trying to get this cleaned up and deployed shortly.

**Comment by GUI** [comment]
@PjEdwards: Sorry for the long delay on this, but I think everything's now live, and hopefully all this CI stuff is better cleaned up as part of #166 (so you should only get notifications from GitHub Actions if things fail, or you can check the status of things here: https://github.com/NREL/developer.nrel.gov/actions).

**Comment by PjEdwards** [comment]
Awesome, thanks!
