### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by cx971111** [NREL/developer.nrel.gov#162]
I was following the API instruction for Solar Data Download at this url (https://nsrdb.nrel.gov/data-sets/api-instructions.html), but after replacing the 'api_key' and 'your_email' with what I requested through [https://developer.nrel.gov/signup/](url), I received the error message "HTTP Error 400: Bad Request". What happened and what can I do?

Thanks

**Comment by PjEdwards** [comment]
A 400 error can be caused by many things, the most common is an invalid set of query parameters. Does the response include a JSON object with a message providing validation error details?

**Comment by hazilo** [comment]
Hey, I've got the the same over here, 400 bad request, here's the result (the email is valid, I just obfuscated it for obvious reasons):

{"inputs":{"names":"tmy","wkt":"POINT(-77.75 36.15)","mail":"xxx.xxx@xxx.com","interval":"60"},"metadata":{"version":"2.0.0"},"status":400,"errors":["The required 'email' parameter must be a valid email address"]}

**Comment by PjEdwards** [comment]
@hazilo In your case it looks like you are providing a "mail" parameter, however the required parameter name is "email".

**Comment by hazilo** [comment]
I see it now, it was "mail" in the whole API description when I designed our software with it in 2018... was it changed recently? This is breaking all our legacy software...

**Comment by PjEdwards** [comment]
We do support receiving POST requests. can you share an example POST request that is failing? With that I can debug and figure out what's causing the 400s.

**Comment by hazilo** [comment]
https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?api_key=xxx
post parameters: 
api_key=xxx
names=tmy
wkt=POINT(Longitude Latitude)
email=xxx@yyy.com
interval=60

**Comment by PjEdwards** [comment]
@hazilo I'm not able to reproduce this. Using a valid API key, email address, and wkt value and submitting a request like this via the POST method works for me. It may be something in the way you are formulating your request. Typically a 400 response will include some JSON with an error message... this message may offer a clue if some of your params are invalid.  In my test I simply used URL params like so: https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?names=tmy&wkt=POINT(-80 41)&email=paul.edwards@nrel.gov&interval=60&api_key={{api_key}} . You can also follow the examples at the bottom of this page for additional guidance: https://developer.nrel.gov/docs/solar/nsrdb/guide/

**Comment by cx971111** [comment]
problem solved

**Comment by pkhorana** [comment]
> @hazilo I'm not able to reproduce this. Using a valid API key, email address, and wkt value and submitting a request like this via the POST method works for me. It may be something in the way you are formulating your request. Typically a 400 response will include some JSON with an error message... this message may offer a clue if some of your params are invalid. In my test I simply used URL params like so: https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?names=tmy&wkt=POINT(-80 41)&email=[paul.edwards@nrel.gov](mailto:paul.edwards@nrel.gov)&interval=60&api_key={{api_key}} . You can also follow the examples at the bottom of this page for additional guidance: https://developer.nrel.gov/docs/solar/nsrdb/guide/

When I try this with POINT(80 40) it works, but when I use POINT(32.49 -84.18), which is a latitude and longitude I have downloaded data from in the NSRDB Map Viewer itself, it gives me this error:

"errors": [
        "No data available at the provided location",
        "Data processing failure."
    ]

Why is it not giving me data for this location?
