### ISSUE TITLE
WIND Toolkit Forecast Data

### ISSUE THREAD

**Issue by marktracy03** [NREL/developer.nrel.gov#164]
I am trying to download forecast data from the Wind Integration National Dataset Toolkit via the API (or another way if it is not possible to use the API). On NREL's site it says, “The forecast data set includes forecasts for 1-hour, 4-hour, 6-hour, and 24-hour forecast horizons,” but I have been unable to download anything other than 5-minute real time data from the API (quoted: https://www.nrel.gov/grid/wind-toolkit.html). Any help would be greatly appreciated.

**Comment by PjEdwards** [comment]
@marktracy03 The forecast data isn't available via the API. That data is part of the techno-economic subset which can be found on S3 at

https://registry.opendata.aws/nrel-pds-wtk/

look for: arn:aws:s3:::nrel-pds-wtk/wtk-techno-economic/pywtk-data/
