### ISSUE TITLE
WIND Toolkit HTTP Error 400 [Data Processing Failure] and Not Found

### ISSUE THREAD

**Issue by jeeptjinva** [NREL/developer.nrel.gov#169]
Using the API to gather WIND Toolkit data seem to be broken.

The link formats (below) worked early last week, and now return Bad Request via Python and a Data Processing Failure when I use the link in a web browser.

https://developer.nrel.gov/api/wind-toolkit/wind/wtk_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}

or when updated to v2 of WIND Toolkit

https://developer.nrel.gov/api/wind-toolkit/v2/wind/wtk_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}

Returns "Not Found."

**Comment by PjEdwards** [comment]
@jeeptjinva We are in the midst of an unscheduled data upload which has interrupted our services. We had hoped to complete this over the weekend, however due to the size of the data and some technical difficulties it is taking us longer than planned. I’ll let you know when the data has been restored. Apologies for the inconvenience!

**Comment by TimurDela** [comment]
Hello, has this been resolved?
Even though the site-count API return wtk=1 for the location I am interested in, all I get from  /api/wind-toolkit/v2/wind/wtk_download.csv is 'Not Found' (no error message).

**Comment by Shubham04111** [comment]
I still cant download the CSV files for many wind locations in India. I think this work is still broken.
