### ISSUE TITLE
HTTP Error 429: Too Many Requests for ~3000 geographic points

### ISSUE THREAD

**Issue by madalsa** [NREL/developer.nrel.gov#170]
I'm trying to scrape TMY 2018 temperature for almost ~3000 points in continental United States (think county centers) and getting too many requests error. I'm looping over the specific lat/lon and as given in the [ documentation ](https://developer.nrel.gov/docs/solar/nsrdb/python-examples/). I'm not sure if I should retry (didn't get a retry-after header along) or I have been restricted, but appreciate if there's a more elegant way to approach this.

Thanks!

**Comment by PjEdwards** [comment]
I think [these docs](https://developer.nrel.gov/docs/solar/nsrdb/guide/) may be more appropriate for your use case. 3000 points should be do-able with a few well constructed multi-point requests.

**Comment by madalsa** [comment]
I can open a new issue for this but a quick follow-up - air_temperature from NSRDB for a particular year, say 2018, is TMY temperature or MERRA 2 values? For TMY3 values, is it necessary to go through SAM?

**Comment by madalsa** [comment]
> I think [these docs](https://developer.nrel.gov/docs/solar/nsrdb/guide/) may be more appropriate for your use case. 3000 points should be do-able with a few well constructed multi-point requests.

I can open a new issue for this but a quick follow-up - air_temperature from NSRDB for a particular year, say 2018, is TMY temperature or MERRA 2 values? For TMY3 values, is it necessary to go through SAM? Thank you for your quick response - appreciate it!

**Comment by PjEdwards** [comment]
Let me ask the team about that and get back to you.

**Comment by madalsa** [comment]
> Let me ask the team about that and get back to you.

Thank you for that!

**Comment by kurt-rhee** [comment]
Hey @PjEdwards are there any docs on how to download multiple years at the same time? All of the examples I have found in the documentation show how to download one year.

**Comment by PjEdwards** [comment]
Yeah, all of the endpoint-specific docs have details on all available input parameters. The `names` param accepts a comma delimited list of years https://developer.nrel.gov/docs/solar/nsrdb/psm3-download/#request-parameters

Regarding your question above about the model details, I dropped the ball on that. I think your best bet for science questions is to post at  https://nsrdb.nrel.gov/contact-us.html. That will go to a better audience for that type of intel.

**Comment by kurt-rhee** [comment]
Awesome thank you!

**Comment by PjEdwards** [comment]
Doh! Didn't pay close attention. Let me know if I can do anything else for you. 
P
