### ISSUE TITLE
Reopt Lite: All output load data returning as 2017

### ISSUE THREAD

**Issue by l-jacob** [NREL/developer.nrel.gov#172]
Hello. I've run a few calls to the API inputting the same data. No matter what value I give "LoadProfile" > "year" it returns
"year" : 2017

I've tried this with identical input information (with "monthly_totals_kwh") changing "year" for 2016, 2018 and 2020. Each time it returns "year": 2017 registered as the input.

Is Reopt Lite only running on 2017 weather data? Thanks.

**Comment by GUI** [comment]
@NLaws, @sakshi-mishra, @t-kwasnik: Is this something one of you can answer regarding the REopt Lite API?

**Comment by NLaws** [comment]
From https://developer.nrel.gov/docs/energy-optimization/reopt-v1/ for `LoadProfile.year`:


>  Year of Custom Load Profile. If a custom load profile is uploaded via the loads_kw parameter, it is important that this year correlates with the load profile so that weekdays/weekends are determined correctly for the utility rate tariff. **If a DOE Reference Building profile (aka 'simulated' profile) is used, the year is set to 2017 since the DOE profiles start on a Sunday.**

**Comment by l-jacob** [comment]
Thank you! That answers my question.
