### ISSUE TITLE
Solar resource files used for Australia stations

### ISSUE THREAD

**Issue by kazanture** [NREL/developer.nrel.gov#174]
Hi,
I am trying to understand PVWatts API results better.
One part the underlying library uses is a black box for me. the Solar resource file (solar_resource_file).
When I made a request the API returns to me and tells it is using for example ""solar_resource_file": "947670.tm3"".
But is it possible to know what is the content of 947670.tm3 ? The reason I am asking when I am manually using SAM or PySAM and if I use energyplus.net data OR [this one](http://climate.onebuilding.org/WMO_Region_5_Southwest_Pacific/AUS_Australia/index.html) I am getting very different AC results (upto 10%) although all the other parameters are same.
It would be great if you can provide the source of that data so I can understand why my analysis very different from PVWatts results.

Thanks in advance!

**Comment by kazanture** [comment]
In addition to above question(but very related) if we are using years 1998-2009 for example; is there a reason we choose this range? Maybe solar cycles(https://en.wikipedia.org/wiki/Solar_cycle_23)? (Then it should be 1996-2008 tho).
Sorry for all noob questions in advance.

**Comment by reger** [comment]
@kazanture there is no access to the files via the pvwatts API, but you can read about the weather data files used by SAM and where to get them here: https://sam.nrel.gov/weather-data.html. The pvwatts API (v6) uses the NSRDB dataset by default, but you can choose to use TMY2, TMY3, or an international stations dataset (see the `dataset` param in the API docs). You can also reach out to the pvwatts team directly via pvwatts@nrel.gov.
