### ISSUE TITLE
WIND Toolkit Power Data Deprecated

### ISSUE THREAD

**Issue by marktracy03** [NREL/developer.nrel.gov#182]
Hello,

It looks like the "power" attribute in the WIND toolkit dataset is deprecated. Hence I can't access the 5-minute real time power data.  Why is this? Is there an alternative way to access this data or similar real-time wind power data?

Thanks,
Mark

**Comment by PjEdwards** [comment]
Hi Mark

We recently upgraded the Wind Prospector to enable the delivery of 5min WTK meteorology data at all hub-heights and locations by leveraging our partnership with the AWS Public Dataset program. Unfortunately, this update means we will no longer be delivering power data. Instead, we recommend one of the following options:
1) Download the deprecated power data directly from AWS: s3://nrel-pds-wtk/wtk-techno-economic/pywtk-data/
2) Download and compute power data using SAM: sam.nrel.gov (ideal for a single site or a few sites and those that want a GUI)
3) Download and compute power data using reV: https://nrel.github.io/reV/misc/examples.running_with_hsds.html (Ideal for those who want power for multiple sites and are familiar with Python)

Best,
Paul

**Comment by reger** [comment]
@PjEdwards can this be closed now?

**Comment by PjEdwards** [comment]
Yes, please
