### ISSUE TITLE
PVWatt request rejected

### ISSUE THREAD

**Issue by jacksontong** [NREL/developer.nrel.gov#186]
We've been using [Guzzle](https://github.com/guzzle/guzzle) to make concurrent requests to pvwatt for 2 years. But today we encountered many request rejected errors and it's very randomly
[https://developer.nrel.gov/api/pvwatts/v6.json?&api_key={api_key}&system_capacity=1&azimuth=90&tilt=20&lat=-38.067679&lon=145.40987&array_type=1&module_type=0&losses=10&dataset=intl&timeframe=hourly&gcr=&inv_eff=97.5&radius=500](https://developer.nrel.gov/api/pvwatts/v6.json?&api_key={api_key}&system_capacity=1&azimuth=90&tilt=20&lat=-38.067679&lon=145.40987&array_type=1&module_type=0&losses=10&dataset=intl&timeframe=hourly&gcr=&inv_eff=97.5&radius=500)
```html
<html>
	<head>
		<title>Request Rejected</title>
	</head>
	<body>
	    An error has occurred. Please consult with your administrator.
		<br>
			<br>Your support ID is: 18241910756903140897
				<br>
					<br>
						<a href=\'javascript:history.back();\'>[Go Back]</a>
	</body>
</html>
```

**Comment by GUI** [comment]
@jacksontong: Sorry for the trouble! Can you try again now? It looks like there was an issue yesterday that was inadvertently blocking some GET requests that also had a body included on the request, but those should be unblocked now. Let us know if you're still seeing any issues, though. If you are, please provide the "support ID" of a new response and we can try to get this resolved. Thanks!
