### ISSUE TITLE
PVWatts API error

### ISSUE THREAD

**Issue by psynapz** [NREL/developer.nrel.gov#188]
When I try to connect via your API, it is saying: 
----
Server Connection Closed
Description: The server requested closed the connection before the transaction was completed.
----
Can you please assist? Everything was working fine until about 10 minutes ago, and we did not have any code changes on our end.

Ref:
https://developer.nrel.gov/api/pvwatts/v5.xml?api_key=XOvO5JaAuzT5j34hdHgnyMEEaTUtsvahlJ2fCY3L&address=4325+Laurel+Grove+Ave%2C+Studio+City%2C+CA+91604&system_capacity=3.1&array_type=1&tilt=20&radius=0&azimuth=270&module_type=0&losses=14

**Comment by IvanChang** [comment]
We are seeing the same problem.

**Comment by dlopuch** [comment]
Can confirm -- getting same error against `GET https://developer.nrel.gov/api/pvwatts/v6.json`

Response status code: 502
Response text: 
```
<HTML>\n<HEAD>\n<TITLE>Server Connection Closed</TITLE>\n</HEAD>\n\n<BODY BGCOLOR="white" FGCOLOR="black">\n<H1>Server Connection Closed</H1>\n<HR>\n\n<FONT FACE="Helvetica,Arial"><B>\nDescription: The server requested closed the connection before\nthe transaction was completed.\n</B></FONT>\n<HR>\n</BODY>\n
```

First observed 2020-12-18 14:25 US/Pacific

**Comment by andrewfister** [comment]
Yes, I'm seeing the same behavior.

**Comment by alexhill113** [comment]
I was getting the same, I am now getting 404 errors instead.

**Comment by dlopuch** [comment]
Can confirm -- was working again over the weekend and Monday, then today started getting 404's with body:

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by alexhill113** [comment]
Hi Dan,

Is there any ETA on a resolution for this issue at all? This has put us at a complete stand-still.


Regards,

Alexander Hill | Software Developer / Analyst | Business Technology | Trinity Solar |

T: (732) 780-3779 Ext. 9312 | F: (732) 780-6671 | E: Alex.Hill@trinity-solar.com<mailto:firstname.lastname@trinity-solar.com>

Corporate HQ: 2211 Allenwood Road | Wall, NJ 07719 | NJ Electrical: 34EB01547400 | NJ HIC: 13VH01244300

For other jurisdictions, please visit: https://www.trinity-solar.com/locations-licenses/

[cid:818fa304-4436-4203-92e5-02e55d1bc5c7]

IRS Circular 230 Disclaimer: To ensure compliance with requirements imposed by the IRS, we inform you that any U.S. federal tax advice contained in this communication (including any attachments) is not intended or written to be used, and cannot be used, for the purpose of (i) avoiding penalties under the Internal Revenue Code, or (ii) promoting, marketing or recommending to another party any transaction or matter addressed herein.
INFORMATION CONTAINED IN THIS E-MAIL TRANSMISSION IS PRIVILEGED AND CONFIDENTIAL. IF YOU ARE NOT THE INTENDED RECIPIENT OF THIS EMAIL, DO NOT READ, DISTRIBUTE OR REPRODUCE THIS TRANSMISSION (INCLUDING ANY ATTACHMENTS). IF YOU HAVE RECEIVED THIS E-MAIL IN ERROR, PLEASE IMMEDIATELY NOTIFY THE SENDER BY TELEPHONE OR EMAIL REPLY.


________________________________

**Comment by dlopuch** [comment]
I think you misunderstood my comment -- I don't work for nrel, I'm
consuming it for my company and so I'm in the same boat as you!

**Comment by reger** [comment]
We are currently experiencing issues with our server environment, but are working to get things resolved. Unfortunately, I have no estimate on when that might be at this time.

**Comment by reger** [comment]
We think things are resolved now and should be back up and running normally. Let us know if you are still experiencing issues.

**Comment by dlopuch** [comment]
Thanks for updating us @reger! We all truly appreciate the work yall do up at NREL, keep it up!
