### ISSUE TITLE
404 on all requests

### ISSUE THREAD

**Issue by alexhill113** [NREL/developer.nrel.gov#189]
I am receiving 404 error for all requests to the PVWatts v6 API.

**Example>>>**

**URL:** 
API KEY excluded

https://developer.nrel.gov/api/pvwatts/v6.json?api_key={API_KEY}&lat=40.15607195829166&lon=-74.10178919529822&system_capacity=10&azimuth=180&tilt=45&array_type=1&module_type=0&losses=8.7&inv_eff=97.8&dc_ac_ratio=1.25&dataset=nsrdb

**RESPONSE:**

```
<html>

<head>
	<title>404 Not Found</title>
</head>

<body>
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>openresty</center>
</body>

</html>
```

**Comment by cyberjus** [comment]
We are seeing this intermittently, maybe 25% of requests.

**Comment by brianvanderlugt** [comment]
Same experience here, although I've been experiencing closer to 80% 404.

**Comment by rinman24** [comment]
Also experiencing 404s intermittently across several machines.

**Comment by reger** [comment]
We are currently experiencing issues with our server environment, but are working to get things resolved. Unfortunately, I have no estimate on when that might be at this time.

**Comment by reger** [comment]
We believe things should be back up and running normally now. Let us know if you are still experiencing this problem.

**Comment by alexhill113** [comment]
@reger things do seem to be working on our end. Thank you for the update.

**Comment by rinman24** [comment]
@reger things are back up on our end too. Thanks.
