### ISSUE TITLE
Pvwatts Access-Control-Allow-Origin header is possibly wrong.

### ISSUE THREAD

**Issue by Lil-Strudel** [NREL/developer.nrel.gov#190]
The API was working perfectly for me a couple of days ago but now it gives me this error (Api Key Excluded):

Access to XMLHttpRequest at 'https://developer.nrel.gov/api/pvwatts/v6.json?api_key=${API Key}&system_capacity=0.31&module_type=1&losses=11.42&array_type=1&tilt=22.62&azimuth=180&lat=40.2968979&lon=-111.6946475' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'domain'.

Looking in the network debugger, the response header is set to domain
![2020-12-22 12_19_07-Window](https://user-images.githubusercontent.com/42657503/102925508-bb935700-4450-11eb-8046-2adf4a3f9512.png)

Is this something that I'm doing wrong, or are other people experiencing this?

**Comment by wss-josh0** [comment]
I’m getting the same error for https://developer.nrel.gov/api/solar/solar_resource/v1.json? and https://developer.nrel.gov/api/utility_rates/v3.json? endpoints.

**Comment by GUI** [comment]
Sorry for the trouble, all! I believe this was related to the same issue in #189. When the 404 error was being returned (which was only happening part of the time), it didn't contain the appropriate CORS headers, so you may have also seen these CORS errors first. But now that the APIs are functioning properly again, this issue should no longer be occurring. But let us know if you're still seeing any issues.
