### ISSUE TITLE
HTTP Error 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by kylebannerman** [NREL/developer.nrel.gov#191]
I am trying to access the API through both my own API key and the DEMO_KEY as on [general API link](https://developer.nrel.gov/docs/cleap/general/), but keep receiving 503 errors. I have tried a few times throughout the past month with no luck. 

Is there a known issue or is there anything I should be doing differently? Please let me know if you need more information on what exactly I am trying to request from the API.

Thank you in advance!

**Comment by Joel-hanson** [comment]
Hi, I am getting similar error. Any updates on this.

**Comment by edatrix** [comment]
hi @kylebannerman and @Joel-hanson sorry for the delayed response and for the inconvenience.  Unfortunately the CLEAP APIs you were trying to reach are no longer supported and were removed.

**Comment by kylebannerman** [comment]
Thanks for the update. Is there another way to access this data or has it been removed entirely?
