### ISSUE TITLE
Downloading archive data from 1990-

### ISSUE THREAD

**Issue by anoushp** [NREL/developer.nrel.gov#192]
Hi,

I am having problems when attempting to download temperature data for 1990s for Indian locations via API. Currently years are limited from 2000-2014. Can we access earlier data somehow?

Thanks you,
Kind regards

**Comment by PjEdwards** [comment]
@anoushp This dataset doesn't include any data outside the 2000-2014 timeframe. I suggest you send your question to https://nsrdb.nrel.gov/contact-us.html and see if anyone there can suggest an alternative data source.

**Comment by anoushp** [comment]
> @anoushp This dataset doesn't include any data outside the 2000-2014 timeframe. I suggest you send your question to https://nsrdb.nrel.gov/contact-us.html and see if anyone there can suggest an alternative data source.

Thanks @PjEdwards, I will use the general contact info you posted!
