### ISSUE TITLE
Unavailable attribute on API request

### ISSUE THREAD

**Issue by jpcarbod** [NREL/developer.nrel.gov#193]
The "midnight_charge" attribute for residential charging strategy does not seem to be available. Getting a "bad request" error from the API when performing a request that includes that value

**Comment by reger** [comment]
@jpcarbod What API are you having problems with?

**Comment by jpcarbod** [comment]
Apologies @reger, I didn't realize this was a general development repository. It's the EVI-Pro Lite API that can be found here: https://developer.nrel.gov/docs/transportation/evi-pro-lite-v1/ 
Both of the API (/daily-load-profile and ​/daily-load-profile​/breakdown present the same issue)

**Comment by reger** [comment]
thanks for letting us know @jpcarbod, we'll look into i

**Comment by amj133** [comment]
@jpcarbod Our apologies, the value you should be using for the `res_charging` param is `timed_charging`.  The docs you correctly referenced were out of date but have since been updated (https://developer.nrel.gov/docs/transportation/evi-pro-lite-v1/) to align with the API.  Thanks for posting!
