### ISSUE TITLE
Alternative Fuel Vehicles api, Help to get electric motorcycle list- HELP!!

### ISSUE THREAD

**Issue by janet-rivas** [NREL/developer.nrel.gov#195]
This is related to Alternative Fuel Vehicles api,
I can make a request using https://developer.nrel.gov/api/vehicles/v1/vehicles.json?api_key=DEMO_KEY,  but there are not electric  motorcycles listed, is there any other API that can list electric motorcycles ?

**Comment by reger** [comment]
Hello @janet-rivas, I believe one of my colleagues already responded to your contact form inquiry about this, so I'm going to close it.
