### ISSUE TITLE
[docs] Broken links to SAM CSV description

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/developer.nrel.gov#196]
Several pages in the docs link to a PDF about the SAM CSV format for weather data, but that url currently 404s.  Example, the "this PDF" link here: https://developer.nrel.gov/docs/solar/nsrdb/psm3-tmy-download/#data-file-format

Lots of pages currently have that link: https://github.com/NREL/developer.nrel.gov/search?q=wfcsv.pdf

I didn't find the current hosting location for that PDF (didn't look very hard though).  Here's a copy of it on the wayback machine: https://web.archive.org/web/20170207203107/https://sam.nrel.gov/sites/default/files/content/documents/pdf/wfcsv.pdf

**Comment by PjEdwards** [comment]
Thanks Kevin. I'm chasing down some updated doc links now and will get those fixed in the soon.

**Comment by PjEdwards** [comment]
The SAM team restored those links for us.
