### ISSUE TITLE
Request permissions to add new proxy path `/api/wave/`

### ISSUE THREAD

**Issue by PjEdwards** [NREL/developer.nrel.gov#197]
We're preparing to serve a new type of data via developer, but when editing the config for our API backend ("Production - GIS Team" I get a permissions error. The permissions appear to be path based. the new path I am adding uses a frontend prefix `/api/wave/`.

![Screen Shot 2021-02-18 at 2 19 13 PM](https://user-images.githubusercontent.com/5941504/108409900-c2daa500-71f4-11eb-88f7-ab012a46a03e.png)

**Comment by GUI** [comment]
@PjEdwards: I think you should have permissions now. Want to give it a spin?

**Comment by PjEdwards** [comment]
Yes, everything working great. Thanks!
