### ISSUE TITLE
energy-incentives:404

### ISSUE THREAD

**Issue by michaeljlee0** [NREL/developer.nrel.gov#20]
I'm trying to integrate the energy-incentives api call into my app but the either the documentation is wrong or that part of the service is currently down.  The [documentation](https://developer.nrel.gov/api/energy-incentives/v1.json?api_key=DEMO_KEY&lat=40&lon=-105&incentive_types=ad_incentives,csp_incentives) says to use the below call but I continue to get a 404 response.

https://developer.nrel.gov/api/energy-incentives/v1.json?api_key=DEMO_KEY&lat=40&lon=-105&incentive_types=ad_incentives,csp_incentives

**Comment by GUI** [comment]
@michaeljlee0: This should be fixed now. Thanks for bringing it to our attention, but sorry for the trouble! Let us know if you have any other questions.
