### ISSUE TITLE
Solar Resource v1 avg_dni is sometimes lowest value

### ISSUE THREAD

**Issue by jblainegarcia** [NREL/developer.nrel.gov#223]
The output given by the example in the docs (https://developer.nrel.gov/api/solar/solar_resource/v1.json?api_key=DEMO_KEY&lat=40&lon=-105) responds with `avg_ghi` having the lowest values, then `avg_lat_tilt` the second lowest, and `avg_dni` the highest.

But I'm coming across other locations producing a different order (https://developer.nrel.gov/api/solar/solar_resource/v1.json?api_key=DEMO_KEY&lat=29&lon=-95), where `avg_dni` is the lowest value.

Based on their respective definitions, I would assume the order of values from lowest to highest would consistently be: `avg_ghi`, `avg_lat_tilt` , `avg_dni` (like the example from docs)

Am I missing something?

**Comment by reger** [comment]
@jblainegarcia Apologies for the slow reply. I don't really have an explanation. I built the API, and it pulls data from a database table built using the SUNY Satellite Solar Radiation model using the model's hourly output for 1998-2009 that was provided at the time. What is returned is what is in that table.

If you haven't already, I would suggest taking a look at the NSRDB APIs (https://developer.nrel.gov/docs/solar/nsrdb/) as they are well supported, and updated more regularly.
