### ISSUE TITLE
Address format for electricity rates unspecified in documentation

### ISSUE THREAD

**Issue by NicholasFry** [NREL/developer.nrel.gov#225]
Hi there. I noticed that the address format is unspecified in the alternative to lat/lon in the electricity rate documentation. Do you have an additional reference for passing this parameter?

https://developer.nrel.gov/docs/electricity/utility-rates-v3/

**Comment by reger** [comment]
Hi Nicholas,

Just "normal" address format, not sure how else to describe it.

`<street address> <city> <state> <postal code>`

For example: `https://developer.nrel.gov/api/utility_rates/v3.json?api_key=DEMO_KEY&address=15013%20Denver%20West%20Parkway%20Golden%20CO%2080401`

Rob.

**Comment by NicholasFry** [comment]
Hi Rob,

Thanks for this. Sorry if the question seems obvious. I am thinking about a little bit of error handling on a user interface. I appreciate the response.
