### ISSUE TITLE
India wind download issue - Multiple years and mutiple coordinates

### ISSUE THREAD

**Issue by ramabgit** [NREL/developer.nrel.gov#245]
Hi,

I'm making calls to India wind API through my own API key. I'm able to download data only for 2014, but not for any other year. Please let me know how can I download data for multiple years. The same url works fine for 2014.
My request URL is below.
https://developer.nrel.gov/api/wind-toolkit/v2/wind/india-wind-download.csv?attributes=pressure_40m%2Ctemperature_100m%2Ctemperature_120m%2Ctemperature_40m%2Ctemperature_80m%2Cwinddirection_100m%2Cwinddirection_120m%2Cwinddirection_40m%2Cwinddirection_80m%2Cwindspeed_100m%2Cwindspeed_120m%2Cwindspeed_40m%2Cwindspeed_80m%2Cpressure_100m&names=2015&email=myemail%40gmail.com&api_key=MY_API_KEY&wkt=POINT(75.36621%2024.726874)
The error I'm getting is below.
"errors": [
        "The required 'names' parameter must be a name in the set [\"2014\"]."

Secondly, I want to supply polygon of coordinates. Please let me know the detail for this.

**Comment by PjEdwards** [comment]
@ramabgit This dataset has only 2014 data available. In order to request data for a region you can use the same API with the following changes:
1. Request using `.json` instead of `.csv`
2. Supply a WKT value of a polygon or multipoint. (There are some examples at https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)

**Comment by ramabgit** [comment]
I'm getting data processing failure for a polygon
{
    "inputs": {
        "body": {},
        "params": {},
        "query": {
            "attributes": "pressure_40m,temperature_100m,temperature_120m,temperature_40m,temperature_80m,winddirection_100m,winddirection_120m,winddirection_40m,winddirection_80m,windspeed_100m,windspeed_120m,windspeed_40m,windspeed_80m,pressure_100m",
            "names": "2014",
            "email": "Ramanathan.DakshinaMurthy@alliancebernstein.com",
            "wkt": "POLYGON(75.36621 24.726874,70.36621 24.726874,70.36621 20.726874,75.36621 20.726874,75.36621 24.726874)"
        }
    },
    "metadata": {
        "version": "2.0.0"
    },
    "status": 400,
    "errors": [
        "Data processing failure."
    ]
}

**Comment by PjEdwards** [comment]
OK I'll take a look. I need to apologize in advance... I've got a backlog of critical tasking including this ticket. I'll get to it as soon as I can but it may be tomorrow before I can start digging around.

**Comment by ramabgit** [comment]
Hi,

I've been trying multiple options. Then finally I got following response. Does that mean Polygon is not accepted for downloading?

"status": 400,
    "errors": [
        "This request type only supports a single point for a single year or TMY type.",
        "Data processing failure."

**Comment by PjEdwards** [comment]
The polygon format is only accepted for `.json` style requests. That message most likely indicates you submitted a polygong with a `.csv` style request? (I haven't forgot about this issue)

**Comment by PjEdwards** [comment]
OK, well after much waiting and suspense it is just a format error in your WKT. Polygons need double parenthesis. IOW try `POLYGON((75.36621%2024.726874,70.36621%2024.726874,70.36621%2020.726874,75.36621%2020.726874,75.36621%2024.726874))`

However in testing I saw that this polygon results in an amount of data that exceeds our rate limits. There is a guide at https://developer.nrel.gov/docs/wind/wind-toolkit/guide/ that breaks down how they work and how to work the system to get the most data.
