### ISSUE TITLE
2021 Data for Physical Solar Model (PSM) v3

### ISSUE THREAD

**Issue by NataliaLopez17** [NREL/developer.nrel.gov#247]
I was just wondering when the 2021 data for the [Physical Solar Model (PSM) v3](https://developer.nrel.gov/docs/solar/nsrdb/psm3-5min-download/)](https://developer.nrel.gov/docs/solar/nsrdb/psm3-5min-download/) would be available.

**Comment by PjEdwards** [comment]
I'll check with the team and let you know.

**Comment by PjEdwards** [comment]
OK, the official answer is:

> Our milestone aims for September 30, 2022 but the past two years, yes the data was available by mid-summer.
