### ISSUE TITLE
India Site count- regarding

### ISSUE THREAD

**Issue by ramabgit** [NREL/developer.nrel.gov#248]
Hi,

I wanted to verify how many sites are providing the data for a region. so I used the site count api call and got following response. Does this mean the India data has only one site? or does this mean the coordinates I have used is getting data from 1 site?

{
    "inputs": {
        "body": {},
        "params": {},
        "query": {
            "wkt": "POINT(75.36621 24.726874)"
        }
    },
    "metadata": {
        "version": "2.0.0",
        "resultset": {
            "count": 1
        }
    },
    "status": 200,
    "outputs": {
        "us-west-coast-virtual-buoy": 0,
        "himawari7": 0,
        "mexico-wtk": 0,
        "offshore-ca": 0,
        "himawari-tmy": 0,
        "full-disc": 0,
        "us-atlantic-virtual-buoy": 0,
        "us-atlantic-hindcast": 0,
        "himawari": 0,
        "india-wind": 1,
        "msg-iodc": 1,
        "offshore-great-lakes": 0,
        "spectral-india-tmy": 0,
        "vietnam-wtk": 0,
        "suny-india-tmy": 1,
        "suny-india": 1,
        "vietnam": 0,
        "psm3": 0,
        "offshore-mid-atlantic": 0,
        "psm3-5min": 0,
        "puerto-rico": 0,
        "offshore-hawaii": 0,
        "philippines": 0,
        "philippines-wtk": 0,
        "offshore-nw-pacific": 0,
        "psm3-tmy": 0,
        "spectral-ondemand": 0,
        "central-asia-wind": 0,
        "hawaii-hindcast": 0,
        "us-west-coast-hindcast": 0,
        "wtk": 0,
        "wtk-srw": 0
    },
    "errors": []
}

I want to know all the sites belonging to india. How do I download data from all sites across india?

**Comment by PjEdwards** [comment]
It is possible to do it through the APIs, however you would have to do some work to craft a series of requests that would allow you to accomplish this within the rate limits of these services. This technique is described at https://developer.nrel.gov/docs/wind/wind-toolkit/guide/. 

However, if you're truly interested in downloading _all_ of the India data you might prefer downloading the full raw dataset directly from AWS from the landing page at https://registry.opendata.aws/nrel-pds-wtk/

**Comment by PjEdwards** [comment]
Specifically about the site_count endpoint, since you requested a single POINT in your WKT, that will only match the closest single site within 50km. That means it will only ever match either 0 or 1 sites. What you are looking for is to make a request with a POLYGON WKT that will return with the number of sites located within the specified polygon.

**Comment by ramabgit** [comment]
Ok. Thanks. That gives some information for me to research. But how do I even get all the coordinates of India?

**Comment by PjEdwards** [comment]
I'd suggest keeping it simple by finding the four corners of a box that contains all of India. Then you could start breaking that down into smaller and smaller squares in a grid pattern until you arrive at a reasonable grid size where each block can be used to craft a request within the rate limits. Since the rate limits are influenced by a few factors in a request it might take a little fiddling to get it dialed in.

**Comment by ramabgit** [comment]
It would be nice if you can include lat and long in the response. 

Anyways, but I tried downloading one another point. it gives me download url but when I try to download, it says URL not found.
here is one such URL.
https://gds-hsds-wtk-files.nrelcloud.org/data/wind/04501aa73898cbd3c7a22be3f62f9152.zip

**Comment by PjEdwards** [comment]
I think the job for that request hasn't run yet. You'll get an email with the same link when the file is truly ready. The resulting files do include the coordinates of the actual site matched. Is that what you meant?

**Comment by ramabgit** [comment]
Great. I'm able to download the file. But it is not having lat and long coordinates in the data

![indiawind-latlong](https://user-images.githubusercontent.com/97115842/149150592-9abb70b1-7e92-4625-b725-6daaad6711cc.PNG)

**Comment by PjEdwards** [comment]
Sorry for the slow turn-around on this. We had a bug. I've deployed a fix so that lat and lon do show up in the downloads now. Thanks again for your feedback!

**Comment by PjEdwards** [comment]
I'm going to close this out. If you have any further issues don't hesitate to let me know!
