### ISSUE TITLE
PSM3 CSV endpoints: "Data Processing Failure"

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/developer.nrel.gov#255]
Hello and happy Friday @PjEdwards!  This morning I and some others are seeing failures on the `psm3-download.csv`, `psm3-tmy-download.csv`, and `psm3-5min-download.csv` endpoints.  I've managed to get one or two requests to work, but repeating the same request fails.  I've not discerned any pattern in the failures.  

Here's an example request that I'd expect to work:
https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-tmy-download.csv?api_key=DEMO_KEY&full_name=Kevin+Anderson&email=kevin.anderson%40nrel.gov&affiliation=NREL&reason=pv+modeling&mailing_list=false&wkt=POINT%28-80.1200+40.0000%29&names=tmy&attributes=ghi&leap_day=false&utc=false&interval=60

And here's the response I get back:

<details>
  <summary>Click to expand!</summary>

```json
{
  "inputs": {
    "body": {},
    "params": {},
    "query": {
      "full_name": "Kevin Anderson",
      "email": "kevin.anderson@nrel.gov",
      "affiliation": "NREL",
      "reason": "pv modeling",
      "mailing_list": "false",
      "wkt": "POINT(-80.1200 40.0000)",
      "names": "tmy",
      "attributes": "ghi",
      "leap_day": "false",
      "utc": "false",
      "interval": "60"
    }
  },
  "metadata": {
    "version": "2.0.0"
  },
  "status": 400,
  "errors": [
    "Data processing failure."
  ]
}
```
</details>

Thanks as always for maintaining these wonderful APIs :)

**Comment by jmartin4nrel** [comment]
I am getting similar "Data Processing Failure" responses with both the psm3-download.csv solar endpoint and the wtk-srw-download wind endpoint. These are the URLs I'm sending (API keys removed) and the responses I'm getting. This was happening yesterday late afternoon; checked again just now and the responses are unchanged.

Wind URL:
https://developer.nrel.gov/api/wind-toolkit/v2/wind/wtk-srw-download?year=2012&lat=33.907295&lon=-116.555588&hubheight=80&api_key={API_KEY}&email=jonathan.martin@nrel.gov
Wind Response:
{"inputs":{"body":{},"params":{},"query":{"year":"2012","lat":"33.907295","lon":"-116.555588","hubheight":"80","email":"jonathan.martin@nrel.gov"}},"metadata":{"version":"2.0.0"},"status":400,"errors":["Data processing failure."]}
Solar URL:
https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-download.csv?wkt=POINT(-116.555588+33.907295)&names=2012&leap_day=false&interval=60&utc=false&full_name=hybrid-systems&email=jonathan.martin@nrel.gov&affiliation=NREL&mailing_list=true&reason=hybrid-analysis&api_key={API_KEY}&attributes=ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle
Solar Response:
{"inputs":{"body":{},"params":{},"query":{"wkt":"POINT(-116.555588 33.907295)","names":"2012","leap_day":"false","interval":"60","utc":"false","full_name":"hybrid-systems","email":"jonathan.martin@nrel.gov","affiliation":"NREL","mailing_list":"true","reason":"hybrid-analysis","attributes":"ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle"}},"metadata":{"version":"2.0.0"},"status":400,"errors":["Data processing failure."]}

Glad to see someone else is getting this, I was going to wait to post and see if it was still happening in the morning but you beat me to it :)

**Comment by craftj2** [comment]
Echoing the statements above. starting seeing this issue with psm3-tmy-download.csv yesterday afternoon

**Comment by jmartin4nrel** [comment]
Appears to be fixed now!
