### ISSUE TITLE
PSM CSV endpoint Fill Flag depends upon version

### ISSUE THREAD

**Issue by mjroth** [NREL/developer.nrel.gov#258]
In the (current) PSM3 CSV endpoint, the header of the CSV includes the "version" tag. I've come across version="3.0.6", "3.1.0", and "3.2.0" for recent years. This is useful information to include.

But I note that the "Fill Flag" changes depending upon the version. 

- For 3.0.6, the Fill Flag is one of [0, 1, 2, 3, 4], which corresponds to the provided header.

- For 3.1.0 and 3.2.0, the Fill Flag seems to be an integer between 0 and 100. It seems to correlate with cloudiness. i.e. 0 or low values seem to be clear sky, while 100 seems to be very cloudy. But doesn't seem to correspond to what is provided in the header.

So, ideally, the documentation could highlight the versioning within PSMv3 and detail exactly what the Fill Flag represents. Note that some quantification of the cloud amount would be **very** helpful.

**Comment by PjEdwards** [comment]
@mjroth This is a reasonable request, but is more relevant to the NSRDB modeling team than it is to to this the API team. The type of documentation you are looking for is generally found at [this page](https://nsrdb.nrel.gov/data-sets/us-data) and any suggestions for updates would be most effectively sent via email to nsrdb@nrel.gov.
