### ISSUE TITLE
Unable to retrieve weather data for a given location

### ISSUE THREAD

**Issue by ryantoussaint** [NREL/developer.nrel.gov#262]
@PjEdwards  I'm seeing 5xx errors on this solar endpoint this morning, for locations that we were able to get data from yesterday.

Sample request:
```
https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-tmy-download.csv?api_key=[...]&names=tgy-2019&utc=false&email=[...]&wkt=POINT(-95.3587672%2029.7658369)
```

The response I get is a 502 Bad Gateway.  Any context is much appreciated, thanks

**Comment by cameroncan** [comment]
We're getting this as well on all requests, including after using the "no_cache=true" flag. Haelp!

**Comment by PjEdwards** [comment]
We suffered a full system failure between about 12:30 EDT and just now. Services are restored but may be laggy as they work through the backlog of requests.
