### ISSUE TITLE
PVWatts V6 API cannot be used for inverters with efficiency below 90%

### ISSUE THREAD

**Issue by grimsa** [NREL/developer.nrel.gov#264]
We ran into a case where PV Watts API returned an Unprocessable Entity response with `["'inv_eff' must be between 90 and 99.5"]` error.

The value we sent was `88` which seems to be correct for `Growatt New Energy SPF 12000T DVM-US MPV` inverter:
![image](https://user-images.githubusercontent.com/8446128/169853589-9420b4b5-830e-4eda-a441-5f0c1569564f.png)

Is the lower bound of allowed `inv_eff` values (currently `90`) something that impacts the estimation logic, or is it an arbitrary value above which most/all inverters should fall?
If the latter, could it be lowered to something below `88` to make it possible to use the API with a wider range of products?

Full request for reference: `https://developer.nrel.gov/api/pvwatts/v6.json?api_key=<redacted>&system_capacity=1.0&module_type=0&losses=12.822227857000012&array_type=1&tilt=22.62&azimuth=0.0&lat=38.6550839&lon=-121.4376944&dataset=nsrdb&timeframe=monthly&dc_ac_ratio=0.3375&inv_eff=88.0`

**Comment by cpaulgilman** [comment]
@grimsa This is an inverter for off-grid PV-battery systems. PVWatts is designed to model grid-connected PV systems with no storage. [Other Growatt](https://www.growatt-america.com/Residential-inverters-8-652.html) inverters designed for grid-connected PV systems have the more typical maximum efficiency values around 98%. Can you tell me more about how you are using PVWatts?
