### ISSUE TITLE
2021 Data for Physical Solar Model (PSM) v3 - Five Minute Temporal Resolution

### ISSUE THREAD

**Issue by NataliaLopez17** [NREL/developer.nrel.gov#275]
I was told that the solar data for the ```https://developer.nrel.gov/docs/solar/nsrdb/psm3-5min-download/```  API would be available mid summer but it's already mid-September and I'm not able to get the download links regarding 2021.

When will the data be available?

**Comment by PjEdwards** [comment]
Hi @NataliaLopez17. Honestly I'm not sure. This forum is a good place  for questions about using the APIs. For questions about data availability and the underlying model technology your best bet is sending email to the mailing list "nsrdb@nrel.gov"
