### ISSUE TITLE
Add option for sub-hourly intervals in SAM format WIND Toolkit data

### ISSUE THREAD

**Issue by williamhobbs** [NREL/developer.nrel.gov#277]
NREL SAM can model sub-hourly wind profiles and the standard WIND Toolkit API has 5-, 15-, 30-, and 60-minute interval options [1]. The SAM format (srw) API [2], however, only has an option for 60-minute intervals, e.g., adding "interval=5" results in a response that includes `"errors":["The optional 'interval' parameter must = 60"]`. 

It would be helpful if the SAM format WIND toolkit API could be updated to allow for 5-, 15-, and 30-minute intervals. 

This is related to https://github.com/NREL/SAM/issues/962. 

[1] https://developer.nrel.gov/docs/wind/wind-toolkit/wtk-download/
[2] https://developer.nrel.gov/docs/wind/wind-toolkit/wtk-srw-download/

**Comment by reger** [comment]
This is dependent on the SAM issue noted above. The SAM team is planning to get to it in the next few months.
