### ISSUE TITLE
Data Processing Failure on https://developer.nrel.gov/docs/solar/nsrdb/psm3-5min-download/

### ISSUE THREAD

**Issue by NataliaLopez17** [NREL/developer.nrel.gov#292]
I have been trying to run the https://developer.nrel.gov/docs/solar/nsrdb/psm3-5min-download/ API, but I keep experiencing the 400 error: "Data Processing Failure". Here is my post request structure: 

```
headers = {
    'content-type': "application/x-www-form-urlencoded",
    'cache-control': "no-cache"
}

url = "https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-5min-download.json?api_key=${API_KEY}&"

payload = "names=2020&leap_day=false&interval=15&utc=false&attributes=ghi,dni,wind_speed,air_temperature,relative_humidity&email=example@gmail.com&wkt=MULTIPOINT((-65.35 18.27,-65.35 18.35,-65.21 18.35,-65.21 18.27,-65.35 18.27))"

response = requests.request("POST", url, data=payload, headers=headers)
```

I have been able to run the API previously using POLYGON but then I encountered a max processing limit which is why I changed it to MULTIPOINT.

**Comment by PjEdwards** [comment]
@NataliaLopez17 We've had ongoing issues with the 5 minute data for the past couple of weeks. However that's resolved now, and the 2021 data is finally available as well. Could you let me know if you're still getting the data processing failure errors now?

**Comment by NataliaLopez17** [comment]
I am still getting the "data processing failure" error.

**Comment by PjEdwards** [comment]
Fully aware that this in an old ticket. @NataliaLopez17 we haven't had issues with this endpoint so I'm going to assume this ticket is closeable.
