### ISSUE TITLE
PSM3 5-minute endpoint returning bad data

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/developer.nrel.gov#293]
@PjEdwards I've started getting bad/impossible data from the 5-minute PSM3 endpoint.  It's not obvious to me what specifically is going off the rails, but I can at least offer some observations from a test file: 

- The DHI, GHI, and DNI fields seem swapped around/mislabeled
- The field labeled DNI seems timeshifted with respect to the others
- Albedo is always either `0.01` or `0.00`, both of which are too low to be realistic
- Air temperature does not show the seasonality I would expect
- Wind direction sometimes goes far out of the valid [0, 360) range

Here's an example file showing some of these issues: https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-5min-download.csv?api_key=DEMO_KEY&full_name=Kevin+Anderson&email=EMAIL&affiliation=NREL&reason=Example&mailing_list=true&wkt=POINT(-105.1749+39.7437)&names=2020&attributes=dhi,dni,ghi,clearsky_dhi,clearsky_dni,clearsky_ghi,air_temperature&leap_day=false&utc=false&interval=5

The (transposed) first row looks like this:
```
Year          2020.0
Month            1.0
Day              1.0
Hour             0.0
Minute           0.0
DHI              0.0
DNI              0.0
GHI             70.0
Clearsky DHI     0.0
Clearsky DNI   943.0
Clearsky GHI  1004.0
Temperature      0.1
```

Any nonzero value of DHI, DNI, GHI, or their clearsky analogs, at midnight local time is quite suspect ;)

**Comment by PjEdwards** [comment]
OK, let me take a look and figure out what's up. Thanks for the note!

**Comment by PjEdwards** [comment]
We're having a little trouble with the data update process. We're trying to deploy to 2021 data, but something is awry and the result is that all the years are now failing. The bad data was the result of pulling from a cached data pointer after the new files were dropped in. I'll keep you posted.

**Comment by PjEdwards** [comment]
We're going to have to restart these uploads from scratch... long story short all years will be out of commission until Monday. I'll report back as soon as it's live again.

**Comment by PjEdwards** [comment]
OK, believe it or not we just got these all uploaded and working again yesterday... including 2018-2021 now.

**Comment by kanderso-nrel** [comment]
Woohoo!  Thanks @PjEdwards.  The pre-2021 data is the re-processed version using the updated models, right?  Are the original pre-2021 datasets still available somewhere for comparison?

**Comment by PjEdwards** [comment]
OK, I've got some details finally. The only version of the old stuff that is being made available is the 30 minute data at  `/psm3`. The rest had to be remade to catch the latest model updates and unfortunately it wasn't feasible to run 2 copies of all of them. There may be copies laying around on Eagle somewhere if you really needed those?

**Comment by kanderso-nrel** [comment]
Thanks @PjEdwards I don't need the old data, I just want to understand what exactly is available from the API :)

> Even that isn't intended to stay forever

Does that mean that the `/psm3` endpoint will be retired, or just the dataset it is currently serving?

**Comment by PjEdwards** [comment]
The endpoint itself will be retired at some point.
