### ISSUE TITLE
UV irradiance fields don't have units listed in data header

### ISSUE THREAD

**Issue by kandersolar** [NREL/developer.nrel.gov#304]
The data header for the various PSM3 endpoints includes the units for each field (e.g. `GHI Units` -> `w/m2`), with the exception of the two new UV irradiance fields `ghuv-280-400` and `ghuv-295-385`.  From the looks of the values I'm guessing they are W/m^2 like the other irradiance fields, but seems like those units ought to be explicitly included next to the others.

Separately: probably changing these spellings will break somebody's code, so I'm not necessarily advocating for any changes here, but as long as I'm complaining about unit symbols I can't help but nitpick the others :wink::

- Temperature units: currently `c`, but is more properly spelled `°C` (note that a bare `C` is technically the symbol for the [coulomb](https://en.wikipedia.org/wiki/Coulomb)) 
- Irradiance units: currently `w/m2`, but is more properly spelled `W/m2` or `W/m^2`
- Angular units: inconsistently `Degree` or `Degrees`

Thanks!

**Comment by PjEdwards** [comment]
Nice find! Will fix as soon as a minute presents itself.

**Comment by PjEdwards** [comment]
This was deployed a while ago... closing.
