### ISSUE TITLE
No data avaialble at provided location in South America with pm3-tmy-download

### ISSUE THREAD

**Issue by kalron1812** [NREL/developer.nrel.gov#312]
When i try to query a location in Brazil say (POINT(-51.6 -16.44) using 
`GET nsrdb/v2/solar/psm3-tmy-download.csv?`
It works fine and it fetches the data, however, if try at a nearby location POINT(-50.5 -29.2)
then i get 

 ```
"status": 400,
    "errors": [
        "No data available at the provided location",
        "Data processing failure."
    ]
```

Which areas do not have the data ? its not clear in the api docs

This is the full query

`GET http://developer.nrel.gov/api/nsrdb/v2/solar/psm3-tmy-download.csv?api_key=XXXXXX=POINT(-50.5 -29.2)&attributes=dhi%2Cdni%2Cghi%2Cdew_point%2Cair_temperature%2Csurface_pressure%2Cwind_direction%2Cwind_speed%2Csurface_albedo%2C%2C%2C&names=tmy-2020`

**Comment by PjEdwards** [comment]
Have a look at the NSRDB Data Viewer at https://nsrdb.nrel.gov/data-viewer. It shows a map with the rough extents of each datasets circled. If you click on any point (or draw a shape, or search an address) it will show you all of the available datasets for that location.
