### ISSUE TITLE
No data available at the provided location

### ISSUE THREAD

**Issue by raceyy** [NREL/developer.nrel.gov#323]
Hi, 

I've been trying to download any data (preferably 10-minute interval data from Himawari) for Perth, Australia (Perth -31.9523, 115.8613). 

It's possible to download data via the NSRDB Data Viewer but not with the NSRDB API request. 

I'm wondering if there is an issue with the API service or if I'm using the wrong satellite, I've tried quite a few variations including taking variable information directly from the NSRDB Data Viewer emailed data but haven't been able to make it work. 

Thanks for your help!

OUTPUT:

Matthews-MacBook-Pro-103:Solar_Modelling racy$ 
{"inputs":{"body":{},"params":{},"query":{"limit":"1","wkt":"POINT(-31.95 115.86)","names":"2013","leap_day":"false","utc":"false","interval":"60","email":"###replaced_for_privacy###","attributes":"clearsky_dni,clearsky_dhi,air_temperature,wind_speed"}},"metadata":{"version":"2.0.0"},"status":400,"errors":["No data available at the provided location","Data processing failure."]}

https://developer.nrel.gov/docs/solar/nsrdb/himawari7-download/
https://developer.nrel.gov/docs/solar/nsrdb/himawari-tmy-download/
https://developer.nrel.gov/docs/solar/nsrdb/himawari-download/

**Comment by raceyy** [comment]
UPDATE:

I've followed the instructions to find the nearest dataset using NSRDB Data Query and it's returned zero datasets.
https://developer.nrel.gov/docs/solar/nsrdb/nsrdb_data_query/

Himarwari covers Australia, does the NSRDB API cover Australia?

Matthews-MacBook-Pro-103:Solar_Modelling racy$ The SSL certificate is invalid.
{"inputs":{"body":{},"params":{},"query":{"wkt":"POINT(-31.95 115.86)"}},"metadata":{"version":"2.0.0","resultset":{"count":0}},"status":200,"outputs":[ ],"errors":[ ]}

**Comment by PjEdwards** [comment]
The data viewer is a good place to browse which datasets are available in a given area: https://nsrdb.nrel.gov/data-viewer. The dataset that covers Australia is PSM based on Himawari, from which there are 2 vintages covering different temporal scopes, and a TMY endpoint available:
https://developer.nrel.gov/docs/solar/nsrdb/himawari-download/
https://developer.nrel.gov/docs/solar/nsrdb/himawari7-download/
https://developer.nrel.gov/docs/solar/nsrdb/himawari-tmy-download/

**Comment by PjEdwards** [comment]
@raceyy Did you ever get your requests working?

**Comment by PjEdwards** [comment]
Fair enough. I realize my initial answer was supremely unhelpful... sharing back at you the docs you'd already referenced in your original statement. We all have bad days I guess.

In case anyone ever looks at this ticket in the future the issue with your request was the well known text has the latitude and longitude swapped. The "no data at location" error coupled with a set of coordinates that are within the relevant extent was the give-away. If I use `POINT(115.86 -31.95)` it returns data as expected.
