### ISSUE TITLE
NSRDB HSDS Data Source Documentation

### ISSUE THREAD

**Issue by dbready** [NREL/developer.nrel.gov#329]
I am interested in pulling a large amount of the NSRDB GHI data covering the continental US over a three year time-span. The 4km, 30minute resolution would be sufficient. Browsing the HSDS service, I can find several potential options, but it is unclear what distinguishes one from the other. I was looking to see if there are any resources which would help me to understand the features/limitations of the available collections.

Not that I require the latest data, but several of the datasets stop in 2020, and so I assume that the folders with 2022 datasets represent the latest supported models. The below groups caught my eye:

- `/nrel/nsrdb/conus/nsrdb_****.h5`
- `/nrel/nsrdb/current/nsrdb_****.h5`
- `/nrel/nsrdb/full_disc/nsrdb_full_disc_****.h5`

Lacking anything concrete, I am tempted to use the `current/` group, but I was hoping for something a little more deliberate. Are the three functionally equivalent for the data I am trying to acquire? If I query years 2019-2022, were there any modelling changes which would disrupt continuity?

Thanks for whatever you can provide.

**Comment by PjEdwards** [comment]
@dbready I'm not knowledgeable enough to confidently give you an answer here. I'd suggest reviewing the dataset documentation from https://nsrdb.nrel.gov/data-sets/us-data. If that doesn't have enough information to answer your questions, send an email directly to the modeling team at nsrdb@nrel.gov. 

(P.S the docs are slightly out of date.... we just released the 2022 data last week. I'll get the API docs and website updated very soon)
