### ISSUE TITLE
How do I get the latitude and longitude of these datasets

### ISSUE THREAD

**Issue by Ewliao** [NREL/developer.nrel.gov#332]
![image](https://github.com/NREL/developer.nrel.gov/assets/84386360/376f0308-e9da-41ef-95d0-7715f934f821)
These data sets have a lot of sites, but I don't know how to get the longitude and latitude of these sites.

**Comment by PjEdwards** [comment]
@Ewliao There is at present no way to get a comprehensive list of site locations for each of these datasets. However it is important to note that these APIs do not require a precise matching location when making a request. The API will return the closest data within approximately 50 kilometers of the requested coordinates. If no data exists within that range a response will be returned that says "No data at provided location". The name of the datasets provides a general guide as to the domain each covers.

To enhance this further, in the next few months we will be releasing a web tool that will make it possible to visually identify the extent of each dataset. This tool will provide tools for downloading directly via the UI, as well as for generating scripts that could be used in code.

**Comment by Ewliao** [comment]
Thank you for your explanation.
