### ISSUE TITLE
API health checks?

### ISSUE THREAD

**Issue by spolloni** [NREL/developer.nrel.gov#335]
Is there a health check for the NREL developer API or specifically the NSRDB
endpoints? We are looking for a way to programmatically and periodically ping
the API to ensure it is up and our credentials (email and key) are valid.

**Comment by PjEdwards** [comment]
@spolloni There is not a specific health check endpoint, however there are a couple you could use for the purpose. The simplest on is to hit https://developer.nrel.gov/api/nsrdb/?api_key=<your_key_here>. This will return a very stripped down HTML page if everything is working. If you want to go one step further and hit an endpoint that does some work, the [site count](https://developer.nrel.gov/docs/solar/nsrdb/site-count/) endpoint would be a good one to try.

**Comment by RIAEvangelist** [comment]
I'd be down to help with this @spolloni and @PjEdwards 

Is there a current plan to work on it?

Seems like a simple enough tool to write.

**Comment by spolloni** [comment]
thank you @PjEdwards, that works!
