### ISSUE TITLE
There was an error while processing your download. NREL support staff have been alerted.

### ISSUE THREAD

**Issue by TheNumenorean** [NREL/developer.nrel.gov#364]
I am getting a lot of these errors when hitting the psm3 endpoint `https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-2-2-download.json`, usually within a minute of submitting the request. The weird part is it sometimes works, and sometimes doesn't, so it seems that my request is correctly formatted.

My script downloads data in chunks, and some of the chunks have succeeded (and i got the email) and some send me the fail email ("There was an error while processing your download. NREL support staff have been alerted."). Any idea what could be happening here?

My code:

```
BASE_URL = "https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-2-2-download.json"
BASE_INPUT = {
    "attributes": "air_temperature,relative_humidity,dhi,ghi,dni,clearsky_dhi,clearsky_ghi,clearsky_dni,wind_speed,wind_direction,surface_pressure",
    "interval": "60",
    "api_key": API_KEY,
    "email": "fjmacagno@gmail.com",
}
YEAR = "2022"


def get_data_for_polygon(polygon: Polygon):
    input_data = {**BASE_INPUT, "wkt": polygon.wkt, "names": [YEAR]}
    data = run_request(BASE_URL, input_data)
    download_url = data["outputs"]["downloadUrl"]
    print(data["outputs"]["message"])
    return download_url


def run_request(url: str, input_data) -> dict:
    response = requests.post(url, input_data, headers={"x-api-key": API_KEY})

    if response.status_code != 200:
        print(
            f"An error has occurred with the server or the request. The request response code/status: {response.status_code} {response.reason}"
        )
        print(f"The response body: {response.text}")
        exit(1)

    try:
        response_json = response.json()
    except:
        print(
            f"The response couldn't be parsed as JSON, likely an issue with the server, here is the text: {response.text}"
        )
        exit(1)

    if len(response_json["errors"]) > 0:
        errors = "\n".join(response_json["errors"])
        print(f"The request errored out, here are the errors: {errors}")
        exit(1)
    return response_json
```

**Comment by PjEdwards** [comment]
@TheNumenorean Are you still seeing these errors? 

In reading the logs I see the intermittent failures peaked on the 15th and the last couple were on the 17th. I believe these to be some random issues due to the system being overloaded as opposed to any specific problem with your requests or any bugs in the codebase.

**Comment by TheNumenorean** [comment]
I was able to get through my set of requests by retrying them after some time; every request ended up succeeding. Glad to confirm it wasn't on my end, so perhaps i can put in a request for more explicit error messages? I would happily, for instance, dynamically decrease my request rate if it would help avoid server issues.

**Comment by PjEdwards** [comment]
> ... perhaps i can put in a request for more explicit error messages?

Request noted. It's a great idea, thanks!
