### ISSUE TITLE
how to use file_id in PVWatts v.5

### ISSUE THREAD

**Issue by grandpasknob** [NREL/developer.nrel.gov#38]
Newbie here.  I'd expect the following query to work (using the TMY2 solar file name returned from a previous lat-long-based query):

https://developer.nrel.gov/api/pvwatts/v5.json?api_key=DEMO_KEY&file_id="93738.tm2"&system_capacity=4&azimuth=180&tilt=40&array_type=1&module_type=1&losses=10

but it returns 

"errors":["Unable to load data file for file_id specified: \"93738.tm2\""]

leaving out various combinations of quote marks and the tm2 name extension don't help; can you?

**Comment by GUI** [comment]
`file_id` actually needs to be a valid `id` returned by the [Solar Dataset Query API](https://developer.nrel.gov/docs/solar/data-query-v1/), so here's an example:

https://developer.nrel.gov/api/pvwatts/v5.json?api_key=DEMO_KEY&file_id=0-93738&system_capacity=4&azimuth=180&tilt=40&array_type=1&module_type=1&losses=10

I've tried to [update](https://github.com/NREL/developer.nrel.gov/commit/7b3781d3c2ac6bead3048e2968ff68891e32a876) the documentation to clarify this usage.

This `id` is slightly different than the `solar_resource_file` you see in the PVWatts results (I believe the ID is prefixed with a numeric identifier that denotes the dataset the file is from).

Let us know if that doesn't make sense or you have any other questions.

@reger: In the `station_info` part of the PVWatts response, we currently return `solar_resource_file`, but do you have any thoughts about also returning this information in the `file_id` notation too? It seems like that could maybe be handy for this type of usage where you want to replicate an earlier call against an explicit file ID (but without having to first use the Solar Dataset Query API).

**Comment by grandpasknob** [comment]
Thanks.  That resolves my issue.
