### ISSUE TITLE
Wind API: Data Source?

### ISSUE THREAD

**Issue by chrisd31** [NREL/developer.nrel.gov#40]
I'd like to know where can I find documentation regarding what is the data source of the wind API. 

For instance, does all the sites have anemometers at 100 m? Is there a list that contains all the available Site Ids?

**Comment by reger** [comment]
@jduckworth  can you answer this?

**Comment by GUI** [comment]
Going to close this, since I think there's additional links that cover this in the docs, but let us know if anything isn't clear.
