### ISSUE TITLE
Undefined Variable: "$font-family-base"

### ISSUE THREAD

**Issue by PjEdwards** [NREL/developer.nrel.gov#49]
execute `./bin/middleman server` and view http://localhost:4567 and see error: 
**Error Compiling CSS Asset Sass:SyntaxError: Undefined Variable: "$font-family-base"**

execute `./bin/middleman build` fails with error: 
**Undefined variable: "$font-family-base". (Sass::SyntaxError)**

I just merged the latest from the home repo into my fork an hour ago. 
Seems like a variable needs to be defined somewhere, but where?

**Comment by GUI** [comment]
Hm, I wasn't able to reproduce this. I just did a fresh clone, `bundle install --binstubs`, and `./bin/middleman build`, and I didn't get any errors.

Have you `bundle install`ed? That variable comes from bootstrap, so as long as bootstrap's sass file is installed and getting included, that variable should be defined (but it seems like if bootstrap-sass were missing entirely, you'd be getting a different type of error, so this is still puzzling). Do you have any changes on your fork besides what's in master?

**Comment by PjEdwards** [comment]
Well dang. I did indeed do a `bundle install --binstubs` which worked out fine. I don't have any changes in my fork (as in the 2 should be identical at this point). 

I will try making fresh clone of this master and see if the results are different.

**Comment by PjEdwards** [comment]
Same results. Do you think this is a problem? 

'$ ruby --version'
'ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin14.5.0]'

**Comment by PjEdwards** [comment]
Switching to this made it all happy again. I don't know why 2.0.0 was my default... I suppose the Mac shipped that way.

`$ ruby --version`
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]`

**Comment by GUI** [comment]
Ah, interesting. Well definitely good to know that we apparently have some Ruby compatibility issues that don't surface in a particularly obvious way. Thanks for tracking that down!
