### ISSUE TITLE
Wind Toolkit Data API returns ZIP files, not friendly for consuming

### ISSUE THREAD

**Issue by GUI** [NREL/developer.nrel.gov#5]
Feedback from our [API Usability Testing](http://18f.github.io/API-Usability-Testing/): The [Wind Toolkit Data API](http://developer.nrel.gov/docs/wind/wind-toolkit-extract/) returns a ZIP file containing a CSV. This makes it inconvenient to deal with for a few reasons:
- ZIP files aren't immediately consumable. They must first be saved and then decompressed before use, which is not convenient for API consumers.
- Errors are returned as JSON, making things inconsistent and meaning the client has to account for parsing both JSON and zip files.
- It's not clear that ZIP files save any sort of bandwidth, since we could gzip the straight CSV response. This would allow any client that supports the more standard gzip compression to transparently receive a compressed response without having to deal with temporary files.

**Comment by PjEdwards** [comment]
There is a version of the endpoints that accept the `.csv` format, allowing for a direct CSV file download. The `.zip` feature is required for endpoints that provide access to anywhere from 1 to 1000s of CSV files in a single request. Perhaps this needs to be more clearly described in the docs?

**Comment by PjEdwards** [comment]
Interestingly, the only [example in the docs](https://developer.nrel.gov/docs/wind/wind-toolkit/wind-toolkit-extract/#examples) is using the `.csv` form...

**Comment by PjEdwards** [comment]
I feel like we should close this one as "Will Not Address". These APIs are constrained by what is possible given the size of the base data.
