### ISSUE TITLE
National Solar Radiation Database API (sscapi) Problem

### ISSUE THREAD

**Issue by CSFlorin** [NREL/developer.nrel.gov#55]
I'm not sure sure if this is a problem with the API or on my part, but the channels of support seem rather limited, so I wanted to ask here in case it helps my chances of getting an answer.

Here is my question.

I get the following error when trying to run a SAM simulation (step 2 here: https://nsrdb.nrel.gov/api-instructions). I'm unsure of what this error actually means, but from what it seems, it says the ssc.dylib is not found, but it is indeed in the directory. I leave the path site.addsitedir('/Applications/sam-sdk-2015-6-30-r3/languages/python/'), because I simply put the SDK in my Applications folder, so this should not be the problem. I have a csv file from Step 1 that I want to perform a simulation on, but I just can't get past this error for some reason. Any ideas?

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-11-76e9347e1c3e> in <module>()
      4 site.addsitedir('/Applications/sam-sdk-2015-6-30-r3/languages/python/')
      5 import sscapi
----> 6 ssc = sscapi.PySSC()
      7 
      8 # Resource inputs for SAM model:

/Applications/sam-sdk-2016-3-14-r3/languages/python/sscapi.pyc in __init__(self)
     21                                 self.pdll = CDLL("ssc.dll")
     22                 elif sys.platform == 'darwin':
---> 23                         self.pdll = CDLL("ssc.dylib")
     24                 elif sys.platform == 'linux2':
     25                         self.pdll = CDLL('ssc.so')   # instead of relative path, require user to have on LD_LIBRARY_PATH

/Users/Florin/anaconda2/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360 
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

OSError: dlopen(ssc.dylib, 6): image not found

Thanks,

Florin

**Comment by reger** [comment]
I would try adding the directory the dylib is located in to `LD_LIBRARY_PATH`

**Comment by CSFlorin** [comment]
Thanks a bunch; that worked! I would hope a comment is put in the relevant lines indicating that it may need the complete path
