### ISSUE TITLE
Timezone of hourly results

### ISSUE THREAD

**Issue by vizath** [NREL/developer.nrel.gov#65]
Hi,
When using pvwatts-v5, what is the timezone of the hours in the `ac/dc/etc..` array when the `timeframe=hourly` ?

In other words, does it starts at `2017-01-01T00:00:00-00:00` or `2017-01-01T00:00:00-07:00`.

Thanks

**Comment by reger** [comment]
@vizath, the timezone is the local timezone of the climate station used, as noted in the `station_info` section of the response.
