### ISSUE TITLE
CORS header caching problem.

### ISSUE THREAD

**Issue by BertoMejia** [NREL/developer.nrel.gov#67]
There is a small bug with your API when using CORS. I am using your Transportation, Alternative Fuel Stations  API, and I can get the data with no problem the first time. However, if I go to another website that pulls the same API, the API uses the origin from the last website used. It seems to be a caching problem with the headers. Below is the error I see in the console in Chrome (on windows 7).

XMLHttpRequest cannot load https://developer.nrel.gov/api/alt-fuel-stations/v1.json?fuel_type=ELEC&ev_. The 'Access-Control-Allow-Origin' header has a value 'https://www.first-url.com' that is not equal to the supplied origin. Origin 'https://second-url.com' is therefore not allowed access.

Can you please look into the headers to make sure they are not caching?

Alternatively, you could add a JSONP file format. This would be would be much easier, and would eliminate   this problem. All that needs to be done is to add the current JSON format into a callback function.

Please let me know if I can help.

**Comment by GUI** [comment]
@BertoMejia: My apologies for the super belated response. This totally slipped past me! But I really appreciate you bringing this to our attention, and sorry for the trouble this caching behavior may have caused you. I believe the issue should now be resolved. Our responses now set the CORS header as `Access-Control-Allow-Origin: *`, which should work for all origins regardless of the cached status.

Let us know if you're still seeing any issues, though.

**Comment by BertoMejia** [comment]
Thanks for the response. It is still giving an error. Now it is giving the following error:

XMLHttpRequest cannot load https://developer.nrel.gov/api/alt-fuel-stations/v1.json?fuel_type=ELEC&ev_…or_type=all&access=public&api_key=x. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://www.domain.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Can you please look into this a little further? Thank you.

**Comment by GUI** [comment]
@BertoMejia: Are you making the XHR request with [`withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) set to true? If so, is there a reason for enabling this? I don't think it should be necessary (since we shouldn't need any cookies sent on the request), but let us know, and we can try to get to the bottom of this.
