### ISSUE TITLE
confusion about file download

### ISSUE THREAD

**Issue by maryamag85** [NREL/developer.nrel.gov#72]
Hi. I would like to download the weather and also the PV power generation data in a specific location, I can download the first part but I stuck doing the second part. Is this data available? is there any better manual using the data rather than this ? https://nsrdb.nrel.gov/api-instructions ? I could not understand how to make different url for the mentioned datasets. no clear link to the file naming and making the actual url. 
I would appreciate it if you make it more clear for a usual user. 

Regards

**Comment by GUI** [comment]
@PjEdwards: Looping you in on this (very belatedly, sorry all!), since you might have a better idea on this.

**Comment by PjEdwards** [comment]
Hi @maryamag85 

I would recommend that you review the API specific documentation for details on the options available for crafting download URLs. The [usage guide](https://developer.nrel.gov/docs/solar/nsrdb/guide/) contains some general guidelines and optimizations that can be applied. The [PSM v2](https://developer.nrel.gov/docs/solar/nsrdb/psm_data_download/) and [PSM v3](https://developer.nrel.gov/docs/solar/nsrdb/psm3_data_download/) pages provide the specifics that you are looking for.

**Comment by GUI** [comment]
Thanks, Paul. Going to go ahead and close this, but let us know if you have any further questions.
