### ISSUE TITLE
Hourly AC system output array dose not give date and time?

### ISSUE THREAD

**Issue by ncashwin** [NREL/developer.nrel.gov#80]
Can any one help me to understand while using PVWatts V5 API with timeframe=hourly, how to relate ac output array to the actual time. I have noticed array has 8760 element, dose this means next 8760 hrs or is it for the current year starting from Jan 1st.

Thanks for you support.

**Comment by reger** [comment]
It is 8760 hours starting at Jan 1.

**Comment by ncashwin** [comment]
@reger Thanks.
