### ISSUE TITLE
Duplicate dates

### ISSUE THREAD

**Issue by tyokota** [NREL/developer.nrel.gov#81]
I recently accessed the PSM3 API. I noticed that 2-28 hour 0-23 was repeated twice in the set when looking at the tmy series.

**Comment by tyokota** [comment]
Actually, I also noticed that only half-day 12/30 and 12/31 were recorded. Is this intentional? Seems like this API is broken.

**Comment by PjEdwards** [comment]
@tyokota thanks for the heads up. I'll look into it.

**Comment by reger** [comment]
@PjEdwards is this resolved? Can we close it?

**Comment by PjEdwards** [comment]
yes, plz close
