### ISSUE TITLE
API is returning Yellowknife as closest station

### ISSUE THREAD

**Issue by cbuxton71** [NREL/developer.nrel.gov#85]
I have been using the API successfully for obtaining data for the last year. Today I noticed that it is now returning Yellowknife,NT as the closest station, even though I am using a Lat-Long in Calgary, AB.  Has something changed to prevent me using this sort of query?

https://developer.nrel.gov/api/pvwatts/v6.json?api_key=xxxxxxxxxxxxxxxxxxxxxxxxxx&lat=51.11&lon=-114.02&radius=0&system_capacity=1&azimuth=180&tilt=51.11&array_type=1&module_type=0&losses=22&dataset=intl

**Comment by reger** [comment]
The PVWatts team decided to remove some sites from the `intl` dataset which they considered redundant with the addition of the `nsrdb` dataset. The NSRDB dataset uses the latest NREL solar data. It appears that the Calgary site was one of the ones removed.

Apologies for any confusion or inconvenience.
