### ISSUE TITLE
504 Gateway Timeout error

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#89]
I've started receiving this error on requests to the solar nsrdb_9105 data set after a very long wait period. The code and URL requests generating this error worked as recently as yesterday. Any idea on what the problem might be? here is a sample url generating this (this is the sample url from the documentation)

https://developer.nrel.gov/api/solar/nsrdb_9105_download.json?api_key=DEMO_KEY&full_name=Sample+User&email=sample@email.com&affiliation=Test+Organization&reason=Example&mailing_list=true&wkt=POINT(-104.6777+38.2726)&names=1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005&attributes=dhi,dni,ghi,dew_point,temp_dryb,atm_pres,rel_hum,etr,etrn,precip_wat,aer_opt_dpth,wind_spd&leap_day=true&utc=true

**Comment by GUI** [comment]
@craftj2: Sorry for the trouble. A few of our APIs, including this NSRDB API, are currently unavailable. We're working on getting them restored as soon as we can and will update you once it's back online.

**Comment by GUI** [comment]
Service was restored to this API on Friday evening. Let us know if you're still seeing issues, and apologies for any inconvenience.

**Comment by craftj2** [comment]
I am still having problems. I get a different response now:

Request rejected

An error has occurred. Please consult with your administrator.

Your support ID is: 8236775082270549914
