### ISSUE TITLE
Request rejected?

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#90]
This is a follow up to issue #89, 504 Gateway Timeout Error. I am still having problems with the solar nsrdb_9105 data set. I get a different response now:

Request rejected

An error has occurred. Please consult with your administrator.

Your support ID is: 8236775082270549914

**Comment by GUI** [comment]
@craftj2: Sorry for the troubles. We're looking to get this resolved.

@PjEdwards: Just looping you in here, in case you're hearing of other users running into this. I've filed a ticket with ITS about this.

**Comment by GUI** [comment]
@craftj2: Can you try again and let us know if you're still running into any issues?

**Comment by craftj2** [comment]
It looks like we are back in business - thank you for the quick response!
